using PKHeX.Core;
using System;
using System.Collections.Generic;

namespace SysBot.Pokemon.Discord;

public static class TradeEmbedDataBuilder
{
    private static readonly HashSet<ushort> ParadoxSpecies = new()
    {
        984, 985, 986, 987, 988, 989, 990, 991, 992, 993,
        994, 995, 1005, 1006, 1009, 1010, 1020, 1021, 1022, 1023
    };

    public static TradeEmbedData Build<T>(T pk, int tradeCode, ulong userId, int uniqueTradeId, int batchTradeNumber, int totalBatchTrades, bool isMysteryEgg, string botName = "") where T : PKM, new()
    {
        var strings = GameInfo.GetStrings("en");
        var data = new TradeEmbedData
        {
            SpeciesId = pk.Species,
            SpeciesName = strings.Species[pk.Species],
            Nickname = pk.IsNicknamed ? pk.Nickname : "",
            IsMysteryEgg = isMysteryEgg,
            IsShiny = pk.IsShiny,
            Type1 = pk.PersonalInfo.Type1,
            Type2 = pk.PersonalInfo.Type2,
            Gender = pk.Gender,
            Level = pk.CurrentLevel,
            NatureName = strings.natures[(int)pk.Nature],
            BallName = strings.balllist[pk.Ball],
            HeldItem = pk.HeldItem > 0 ? strings.itemlist[pk.HeldItem] : "",
            OriginalTrainer = pk.OriginalTrainerName,
            IsLegendary = SpeciesCategory.IsLegendary(pk.Species),
            IsMythical = SpeciesCategory.IsMythical(pk.Species),
            IsSubLegendary = SpeciesCategory.IsSubLegendary(pk.Species),
            IsParadox = ParadoxSpecies.Contains(pk.Species),
            BatchTradeNumber = batchTradeNumber,
            TotalBatchTrades = totalBatchTrades,
            TradeCode = tradeCode,
            UserId = userId,
            UniqueTradeId = uniqueTradeId,
            BotName = botName,
            GameType = typeof(T).Name
        };

        data.FormName = ShowdownParsing.GetStringFromForm(pk.Form, strings, pk.Species, pk.Context);

        Span<int> ivs = stackalloc int[6];
        pk.GetIVs(ivs);
        data.IVs = ivs.ToArray();

        int[] evs = new int[6];
        pk.GetEVs(evs);
        data.EVs = evs;

        data.UsesAVs = pk is PB7;
        if (pk is not PB7)
            data.AbilityName = strings.abilitylist[pk.Ability];

        ushort[] moves = new ushort[4];
        pk.GetMoves(moves.AsSpan());
        data.MoveNames = new string[4];
        for (int i = 0; i < 4; i++)
            data.MoveNames[i] = moves[i] > 0 ? strings.movelist[moves[i]] : "";

        if (pk is IAlpha alpha)
            data.IsAlpha = alpha.IsAlpha;

        // Thumbnail URL
        if (isMysteryEgg)
        {
            data.ThumbnailUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/490.png";
        }
        else if (pk.Species > 0)
        {
            if (!pk.IsShiny && pk.Form == 0)
                data.ThumbnailUrl = $"https://creator.pkm-universe.com/assets/floating/{pk.Species}.gif";
            else
                data.ThumbnailUrl = GetHomeSpriteUrl(pk.Species, pk.Form, pk.IsShiny);
        }

        return data;
    }

    private static string GetHomeSpriteUrl(int species, int form, bool shiny)
    {
        string baseUrl = shiny
            ? "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/shiny/"
            : "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/";
        // Alternate forms (Galarian/Alolan/Hisuian/Paldean, Megas, and popular battle forms) have
        // their OWN PokeAPI sprite id — the base {species}.png shows the wrong form (e.g. Galarian
        // Moltres rendered as Kantonian). Map (species,form) -> PokeAPI form id; fall back to species.
        if (form > 0 && FormSpriteId.TryGetValue(species * 100 + form, out int fid))
            return $"{baseUrl}{fid}.png";
        return $"{baseUrl}{species}.png";
    }

    // key = species*100 + PKHeX form index  ->  PokeAPI "other/home" sprite id. Auto-generated by the
    // home-itemtest FormMap tool: for every species+form, PKHeX supplies the English form name, it is
    // normalized to PokeAPI's naming convention, and the id is looked up in PokeAPI's real form list —
    // so every entry is a verified match. Covers all regional (Alolan/Galarian/Hisuian/Paldean) and
    // distinct battle forms (Origin/Sky/Resolute/Pirouette/Unbound/Therian/Crowned/riders/masks/etc.).
    // Cosmetic-only forms (Unown letters, Vivillon patterns, Furfrou trims, weather forms) are omitted:
    // they share the base HOME sprite. Mega/Primal forms are intentionally excluded. Regenerate via
    // `dotnet run --project home-itemtest` to add new-generation forms.
    private static readonly System.Collections.Generic.Dictionary<int, int> FormSpriteId = new()
    {
        {1901,10091},{2001,10092},{2501,10080},{2502,10081},{2503,10082},{2504,10083},{2505,10084},{2506,10085},{2508,10158},{2601,10100},{2701,10101},{2801,10102},
        {3701,10103},{3801,10104},{5001,10105},{5101,10106},{5201,10107},{5202,10161},{5301,10108},{5801,10229},{5901,10230},{7401,10109},{7501,10110},{7601,10111},
        {7701,10162},{7801,10163},{7901,10164},{8002,10165},{8301,10166},{8801,10112},{8901,10113},{10001,10231},{10101,10232},{10301,10114},{10501,10115},{11001,10167},
        {12201,10168},{12801,10250},{12802,10251},{12803,10252},{14401,10169},{14501,10170},{14601,10171},{15701,10233},{19401,10253},{19901,10172},{21101,10234},{21501,10235},
        {22201,10173},{26301,10174},{26401,10175},{35101,10013},{35102,10014},{35103,10015},{38601,10001},{38602,10002},{38603,10003},{41301,10004},{41302,10005},{47901,10008},
        {47902,10009},{47903,10010},{47904,10011},{47905,10012},{48301,10245},{48401,10246},{48701,10007},{49201,10006},{50301,10236},{54901,10237},{55001,10016},{55002,10247},
        {55401,10176},{55501,10017},{55502,10177},{55503,10178},{56201,10179},{57001,10238},{57101,10239},{61801,10180},{62801,10240},{64101,10019},{64201,10020},{64501,10021},
        {64601,10023},{64602,10022},{64701,10024},{64801,10018},{67005,10061},{67801,10025},{68101,10026},{70501,10241},{70601,10242},{71001,10027},{71002,10028},{71003,10029},
        {71101,10030},{71102,10031},{71103,10032},{71301,10243},{71801,10181},{71802,10181},{71804,10120},{72001,10086},{72401,10244},{73501,10121},{73801,10122},{74101,10123},
        {74102,10124},{74103,10125},{74301,10150},{74501,10126},{74502,10152},{74601,10127},{75201,10153},{75401,10128},{75801,10129},{77407,10136},{77408,10137},{77409,10138},
        {77410,10139},{77411,10140},{77412,10141},{77413,10142},{77701,10154},{77801,10143},{78401,10146},{80001,10155},{80002,10156},{80003,10157},{80101,10147},{84501,10182},
        {84502,10183},{84901,10184},{87501,10185},{87601,10186},{87701,10187},{88801,10188},{88901,10189},{89001,10190},{89201,10191},{89301,10192},{89801,10193},{89802,10194},
        {90101,10272},{90201,10248},{90501,10249},{91601,10254},{93101,10260},{93102,10261},{93103,10262},{96401,10256},{97801,10258},{97802,10259},{98201,10255},{99901,10263},
        {101701,10273},{101702,10274},{101703,10275},{102401,10276},{102402,10277},
    };
}
